In [3]:
from cProfile import label
from unittest.mock import inplace

# 数据的导入
import pandas as pd
from pandas.conftest import dropna

df = pd.read_csv('data/employees.csv')
# 数据的导出
df = df.tail()
df.to_csv('data/new_employees.csv')

In [11]:
# json
df = pd.read_json('data/data1.json')
print(type(df))
import json
with open('data/test.json', 'r') as f:
    data = json.load(f)
print(type(data))
df = pd.DataFrame(data['users'])
print(type(df))
df

<class 'pandas.DataFrame'>
<class 'dict'>
<class 'pandas.DataFrame'>

   id name  age                 email  is_active   join_date
0   1  寮犱笁   28  zhangsan@example.com       True  2022-03-15
1   2  鏉庡洓   35      lisi@example.com      False  2021-11-02
2   3  鐜嬩簲   24    wangwu@example.com       True  2023-01-20

In [34]:
# 缺失值的处理
# nan:not a number
import pandas as pd
import numpy as np
s = pd.Series([12,25,np.nan, None, pd.NA])
df = pd.DataFrame([[1,pd.NA,2],[2,3,5],[None,4,6]],columns=['第1列','第2列','第3列'])
print(s)
print(df)
# 查看是否是缺失值
df.isna()
df.isnull()
df.isna().sum()
df.isnull().sum(axis=1)
# 剔除缺失值
print(s.dropna())
print('-'*30)
print(df.dropna()) # 剔除一整条的记录
print(df.dropna(how='all')) # 如果所有值都是缺失值，则删除这一行
print(df.dropna(how='any')) # 如果存在值是缺失值，则删除这一行
print(df.dropna(subset='第1列',thresh=1)) # 如果检查的列至少有一个值不是缺失值，则保留
print(df.dropna(subset='第1列',thresh=1)) # 如果检查的列至少有一个值不是缺失值，则保留
print(df.dropna(axis=1))
# 填充缺失值
df = pd.read_csv('data/weather_withna.csv')
# df.tail()
print(df.isna().sum())
print(df.fillna({'temp_max':20}).tail())
print(df.fillna(df[['temp_max','wind']].mean()).tail())
print(df.ffill().tail())
print(df.bfill().tail())

0      12
1      25
2     NaN
3    None
4    <NA>
dtype: object
   第1列   第2列  第3列
0  1.0  <NA>    2
1  2.0     3    5
2  NaN     4    6
0    12
1    25
dtype: object
------------------------------
   第1列 第2列  第3列
1  2.0   3    5
   第1列   第2列  第3列
0  1.0  <NA>    2
1  2.0     3    5
2  NaN     4    6
   第1列 第2列  第3列
1  2.0   3    5
   第1列   第2列  第3列
0  1.0  <NA>    2
1  2.0     3    5
   第1列   第2列  第3列
0  1.0  <NA>    2
1  2.0     3    5
   第3列
0    2
1    5
2    6
date               0
precipitation    303
temp_max         303
temp_min         303
wind             303
weather          303
dtype: int64
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            NaN      20.0       NaN   NaN     NaN
1457  2015-12-28            NaN      20.0       NaN   NaN     NaN
1458  2015-12-29            NaN      20.0       NaN   NaN     NaN
1459  2015-12-30            NaN      20.0       NaN   NaN     NaN
1460  2015-12-31           20.6      12.2       5.0   3.8    rain
            date  precipitation   temp_max  temp_min      wind weather
1456  2015-12-27            NaN  15.851468       NaN  3.242055     NaN
1457  2015-12-28            NaN  15.851468       NaN  3.242055     NaN
1458  2015-12-29            NaN  15.851468       NaN  3.242055     NaN
1459  2015-12-30            NaN  15.851468       NaN  3.242055     NaN
1460  2015-12-31           20.6  12.200000       5.0  3.800000    rain
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            0.0      11.1       4.4   4.8     sun
1457  2015-12-28            0.0      11.1       4.4   4.8     sun
1458  2015-12-29            0.0      11.1       4.4   4.8     sun
1459  2015-12-30            0.0      11.1       4.4   4.8     sun
1460  2015-12-31           20.6      12.2       5.0   3.8    rain
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27           20.6      12.2       5.0   3.8    rain
1457  2015-12-28           20.6      12.2       5.0   3.8    rain
1458  2015-12-29           20.6      12.2       5.0   3.8    rain
1459  2015-12-30           20.6      12.2       5.0   3.8    rain
1460  2015-12-31           20.6      12.2       5.0   3.8    rain

In [38]:
import pandas as pd
data = {
    "name":['alice','alice','bob','alice','jack','bob'],
    "age":[26,25,30,25,35,30],
    'city':['NY','NY','LA','NY','SF','LA']
}
df = pd.DataFrame(data)
df.duplicated()
df.drop_duplicates(subset=['city'],keep='first')

    name  age city
0  alice   26   NY
2    bob   30   LA
4   jack   35   SF

In [46]:
# 数据类型的转换
df = pd.read_csv('data/sleep.csv')
df.dtypes
df['age'] = df['age'].astype('int16')
df.dtypes
df['gender'] = df['gender'].astype('category')
df.gender
df['is_male'] = df['gender'].map({'Male':False,'Female':True})
df.is_male

0      False
1       True
2      False
3      False
4      False
       ...
395     True
396     True
397     True
398     True
399    False
Name: is_male, Length: 400, dtype: category
Categories (2, bool): [True, False]

In [47]:
#数据变形
import pandas as pd
data = {
    'ID': [1, 2],
    'name':['alice','bob'],
    'Math': [90, 85],
    'English': [88, 92],
    'Science': [95, 89]
}
df = pd.DataFrame(data)
df

   ID   name  Math  English  Science
0   1  alice    90       88       95
1   2    bob    85       92       89

In [61]:
df.T
# 宽表转长表
df2 = pd.melt(df,id_vars=['ID','name'],var_name='科目',value_name='成绩')
df2.sort_values('ID')
# 长表转宽表
df3 = pd.pivot(df2,index=['ID','name'],columns='科目',values='成绩')
df3.sort_values('ID')

科目        English  Math  Science
ID name
1  alice       88    90       95
2  bob         92    85       89

In [78]:
#数据变形
import pandas as pd
data = {
    'ID': [1, 2],
    'name':['alice smith','bob smith'],
    'Math': [90, 85],
    'English': [88, 92],
    'Science': [95, 89]
}
df = pd.DataFrame(data)
df
# 分列
df[['姓','名']] = df['name'].str.split(' ',expand=True)
df = pd.read_csv('data/sleep.csv')
df[['high','low']] = df['blood_pressure'].str.split('/',expand=True)
df.info()
df['high'] = df['high'].astype('int64')
df['low'] = df['low'].astype('int64')
df.info()
print(df['high'].mean())

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   person_id                400 non-null    int64
 1   gender                   400 non-null    str
 2   age                      400 non-null    int64
 3   occupation               400 non-null    str
 4   sleep_duration           400 non-null    float64
 5   sleep_quality            400 non-null    float64
 6   physical_activity_level  400 non-null    int64
 7   stress_level             400 non-null    int64
 8   bmi_category             400 non-null    str
 9   blood_pressure           400 non-null    str
 10  heart_rate               400 non-null    int64
 11  daily_steps              400 non-null    int64
 12  sleep_disorder           110 non-null    str
 13  high                     400 non-null    str
 14  low                      400 non-null    str
dtypes: float64(2), int64(6), str(7)
memory usage: 47.0 KB
<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   person_id                400 non-null    int64
 1   gender                   400 non-null    str
 2   age                      400 non-null    int64
 3   occupation               400 non-null    str
 4   sleep_duration           400 non-null    float64
 5   sleep_quality            400 non-null    float64
 6   physical_activity_level  400 non-null    int64
 7   stress_level             400 non-null    int64
 8   bmi_category             400 non-null    str
 9   blood_pressure           400 non-null    str
 10  heart_rate               400 non-null    int64
 11  daily_steps              400 non-null    int64
 12  sleep_disorder           110 non-null    str
 13  high                     400 non-null    int64
 14  low                      400 non-null    int64
dtypes: float64(2), int64(8), str(5)
memory usage: 47.0 KB
122.19

In [87]:
# 数据分箱
import pandas as pd
df = pd.read_csv('data/employees.csv')
df.head()

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,515.123.4567,AD_PRES,24000.0,NaN,NaN,90.0
1,101,N_ann,Kochhar,NKOCHHAR,515.123.4568,AD_VP,17000.0,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,AD_VP,17000.0,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,IT_PROG,9000.0,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,IT_PROG,6000.0,NaN,103.0,60.0

In [100]:
df1 = df.head(10)[['employee_id','salary']]
pd.cut(df1['salary'],bins=3).value_counts()
pd.cut(df1['salary'],bins=[0,10000,20000,30000]).value_counts()
pd.cut(df1['salary'],bins=[0,10000,20000,30000],labels=['低','中','高']).value_counts()
# pd.cut(df1['salary'],bins=[0,10000,20000,30000],labels=False).value_counts()
df1['收入范围'] = pd.cut(df1['salary'],bins=[0,10000,20000,30000],labels=['低','中','高'])
print(df1)
pd.qcut(df1['salary'],3).value_counts()

   employee_id   salary 收入范围
0          100  24000.0    高
1          101  17000.0    中
2          102  17000.0    中
3          103   9000.0    低
4          104   6000.0    低
5          105   4800.0    低
6          106   4800.0    低
7          107   4200.0    低
8          108  12000.0    中
9          109   9000.0    低

salary
(4199.999, 6000.0]    4
(6000.0, 12000.0]     3
(12000.0, 24000.0]    3
Name: count, dtype: int64

In [107]:
# 睡眠数据
df = pd.read_csv('data/sleep.csv')
df['睡眠质量'] = pd.cut(df['sleep_quality'],bins=3,labels=['差','中','优'])
df.head(10)
df['睡眠质量'].value_counts()
df['gender'].value_counts()

gender
Female    201
Male      199
Name: count, dtype: int64

In [ ]:
# 时间数据的处理
import pandas as pd

In [109]:
# 字符串转换为日期类型
a = pd.to_datetime('2015-2-08')
print(a)

2015-02-08 00:00:00

In [111]:
# dateFrame 日期转换
df = pd.DataFrame({
    'sales':[100,200,300],
    'date':['20250601','20250602','20250603']
})
df['date'] = pd.to_datetime(df['date'])
df['week'] = df['date'].dt.day_name()

   sales       date     week
0    100 2025-06-01   Sunday
1    200 2025-06-02   Monday
2    300 2025-06-03  Tuesday

In [116]:
# csv 日期转换
df = pd.read_csv('data/weather.csv')
df['date'] = pd.to_datetime(df['date'])
# df.info()
df['week'] = df['date'].dt.day_name()
df

           date  precipitation  temp_max  temp_min  wind  weather       week
0    2012-01-01            0.0      12.8       5.0   4.7  drizzle     Sunday
1    2012-01-02           10.9      10.6       2.8   4.5     rain     Monday
2    2012-01-03            0.8      11.7       7.2   2.3     rain    Tuesday
3    2012-01-04           20.3      12.2       5.6   4.7     rain  Wednesday
4    2012-01-05            1.3       8.9       2.8   6.1     rain   Thursday
...         ...            ...       ...       ...   ...      ...        ...
1456 2015-12-27            8.6       4.4       1.7   2.9     rain     Sunday
1457 2015-12-28            1.5       5.0       1.7   1.3     rain     Monday
1458 2015-12-29            0.0       7.2       0.6   2.6      fog    Tuesday
1459 2015-12-30            0.0       5.6      -1.0   3.4      sun  Wednesday
1460 2015-12-31            0.0       5.6      -2.1   3.5      sun   Thursday

[1461 rows x 7 columns]

In [150]:
df = pd.read_csv('data/weather.csv',parse_dates=['date'])
df

           date  precipitation  temp_max  temp_min  wind  weather
0    2012-01-01            0.0      12.8       5.0   4.7  drizzle
1    2012-01-02           10.9      10.6       2.8   4.5     rain
2    2012-01-03            0.8      11.7       7.2   2.3     rain
3    2012-01-04           20.3      12.2       5.6   4.7     rain
4    2012-01-05            1.3       8.9       2.8   6.1     rain
...         ...            ...       ...       ...   ...      ...
1456 2015-12-27            8.6       4.4       1.7   2.9     rain
1457 2015-12-28            1.5       5.0       1.7   1.3     rain
1458 2015-12-29            0.0       7.2       0.6   2.6      fog
1459 2015-12-30            0.0       5.6      -1.0   3.4      sun
1460 2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]

In [156]:
# 日期数据作为索引
print(df.columns)
df.reset_index(inplace=True)
df = df.set_index('date')
# print(df)
print(df.loc['20120101':'20120103'])

Index(['precipitation', 'temp_max', 'temp_min', 'wind', 'weather'], dtype='str')
            precipitation  temp_max  temp_min  wind  weather
date
2012-01-01            0.0      12.8       5.0   4.7  drizzle
2012-01-02           10.9      10.6       2.8   4.5     rain
2012-01-03            0.8      11.7       7.2   2.3     rain

In [157]:
# 时间间隔
d1 = pd.Timestamp('2013-01-15')
d2 = pd.Timestamp('2023-02-05')
d3 = d2 - d1
print(d3)

3673 days 00:00:00

In [164]:
df = pd.read_csv('data/weather.csv',parse_dates=['date'])
df['delta'] = df['date'] - df['date'][0]
df.set_index('delta',inplace=True)
print(df.loc['10 days':'20 days'])

              date  precipitation  temp_max  temp_min  wind weather
delta
10 days 2012-01-11            0.0       6.1      -1.1   5.1     sun
11 days 2012-01-12            0.0       6.1      -1.7   1.9     sun
12 days 2012-01-13            0.0       5.0      -2.8   1.3     sun
13 days 2012-01-14            4.1       4.4       0.6   5.3    snow
14 days 2012-01-15            5.3       1.1      -3.3   3.2    snow
15 days 2012-01-16            2.5       1.7      -2.8   5.0    snow
16 days 2012-01-17            8.1       3.3       0.0   5.6    snow
17 days 2012-01-18           19.8       0.0      -2.8   5.0    snow
18 days 2012-01-19           15.2      -1.1      -2.8   1.6    snow
19 days 2012-01-20           13.5       7.2      -1.1   2.3    snow
20 days 2012-01-21            3.0       8.3       3.3   8.2    rain

In [159]:
days = pd.date_range('2025-01-01', '2025-12-31',freq='W')
print(days)
days = pd.date_range('2025-01-01', periods=10,freq='W')
print(days)

DatetimeIndex(['2025-01-05', '2025-01-12', '2025-01-19', '2025-01-26',
               '2025-02-02', '2025-02-09', '2025-02-16', '2025-02-23',
               '2025-03-02', '2025-03-09', '2025-03-16', '2025-03-23',
               '2025-03-30', '2025-04-06', '2025-04-13', '2025-04-20',
               '2025-04-27', '2025-05-04', '2025-05-11', '2025-05-18',
               '2025-05-25', '2025-06-01', '2025-06-08', '2025-06-15',
               '2025-06-22', '2025-06-29', '2025-07-06', '2025-07-13',
               '2025-07-20', '2025-07-27', '2025-08-03', '2025-08-10',
               '2025-08-17', '2025-08-24', '2025-08-31', '2025-09-07',
               '2025-09-14', '2025-09-21', '2025-09-28', '2025-10-05',
               '2025-10-12', '2025-10-19', '2025-10-26', '2025-11-02',
               '2025-11-09', '2025-11-16', '2025-11-23', '2025-11-30',
               '2025-12-07', '2025-12-14', '2025-12-21', '2025-12-28'],
              dtype='datetime64[us]', freq='W-SUN')
DatetimeIndex(['2025-01-05', '2025-01-12', '2025-01-19', '2025-01-26',
               '2025-02-02', '2025-02-09', '2025-02-16', '2025-02-23',
               '2025-03-02', '2025-03-09'],
              dtype='datetime64[us]', freq='W-SUN')

In [165]:
df = pd.read_csv('data/weather.csv',parse_dates=['date'])
print(df)
# 重新采样
df.set_index('date',inplace=True)
df[['temp_max','temp_min']].resample('YE').mean()

           date  precipitation  temp_max  temp_min  wind  weather
0    2012-01-01            0.0      12.8       5.0   4.7  drizzle
1    2012-01-02           10.9      10.6       2.8   4.5     rain
2    2012-01-03            0.8      11.7       7.2   2.3     rain
3    2012-01-04           20.3      12.2       5.6   4.7     rain
4    2012-01-05            1.3       8.9       2.8   6.1     rain
...         ...            ...       ...       ...   ...      ...
1456 2015-12-27            8.6       4.4       1.7   2.9     rain
1457 2015-12-28            1.5       5.0       1.7   1.3     rain
1458 2015-12-29            0.0       7.2       0.6   2.6      fog
1459 2015-12-30            0.0       5.6      -1.0   3.4      sun
1460 2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]

             temp_max  temp_min
date
2012-12-31  15.276776  7.289617
2013-12-31  16.058904  8.153973
2014-12-31  16.995890  8.662466
2015-12-31  17.427945  8.835616

In [15]:
# 分组聚合
# df.groupby('分组的字段')['聚合的字段'].聚合函数()
import pandas as pd
df = pd.read_csv('data/employees.csv')
df = df.dropna(subset=['department_id'])
df['department_id'] = df['department_id'].astype('int64')
# 计算不同部门的平均薪资
# df.groupby('department_id').groups
df.groupby('department_id').get_group(20)
df2 = df.groupby('department_id')[['salary']].mean()
df2['salary'] = df2['salary'].round(2)
df2 = df2.reset_index().sort_values('salary',ascending=False)
df2 = df.groupby(['department_id','job_id'])[['salary']].mean()
df2

                                salary
department_id job_id
10            AD_ASST      4400.000000
20            MK_MAN      13000.000000
              MK_REP       6000.000000
30            PU_CLERK     2780.000000
              PU_MAN      11000.000000
40            HR_REP       6500.000000
50            SH_CLERK     3215.000000
              ST_CLERK     2785.000000
              ST_MAN       7280.000000
60            IT_PROG      5760.000000
70            PR_REP      10000.000000
80            SA_MAN      12200.000000
              SA_REP       8396.551724
90            AD_PRES     24000.000000
              AD_VP       17000.000000
100           FI_ACCOUNT   7920.000000
              FI_MGR      12000.000000
110           AC_ACCOUNT   8300.000000
              AC_MGR      12000.000000

In [20]:
# 企鹅数据分析
# 1. 导入必要的库
import pandas as pd
import numpy as np
# 2. 导入数据
df = pd.read_csv('data/penguins.csv')
df.head(5)
# df.info()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

In [23]:
# 3. 数据清洗
# 缺失值的检查
df.isna().sum()
df.dropna(inplace=True)
df.isna().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [29]:
# 4. 数据特征的构造
df.head()
df['sex'] = df['sex'].astype('category')
df['bill_ratio'] = df['bill_length_mm']/df['bill_depth_mm']
df['bill_ratio'] = df['bill_ratio'].round(2)
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bill_ratio
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,2.09
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,2.27
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,2.24
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,1.90
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male,1.91
...,...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female,3.45
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,3.27
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,3.21
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,3.05
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,3.10

In [34]:
# 5. 数据分析
# 数据分箱-把体重分为三个等级
labels = ['低','中','高']
df['mass_level'] = pd.cut(df['body_mass_g'],bins=3,labels=labels)
df.head()
print(df['mass_level'].value_counts())
# 按岛屿、性别分组分析
df.groupby(['sex','island']).agg({
    'body_mass_g':['mean','count']
})

mass_level
低    150
中    128
高     55
Name: count, dtype: int64

                  body_mass_g
                         mean count
island    sex
Biscoe    Female  4319.375000    80
          Male    5104.518072    83
Dream     Female  3446.311475    61
          Male    3987.096774    62
Torgersen Female  3395.833333    24
          Male    4034.782609    23

In [36]:
# 1.导入库
import pandas as pd
import numpy as np
# 2.导入数据
df = pd.read_csv('data/sleep.csv')
df.head()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   person_id                400 non-null    int64
 1   gender                   400 non-null    str
 2   age                      400 non-null    int64
 3   occupation               400 non-null    str
 4   sleep_duration           400 non-null    float64
 5   sleep_quality            400 non-null    float64
 6   physical_activity_level  400 non-null    int64
 7   stress_level             400 non-null    int64
 8   bmi_category             400 non-null    str
 9   blood_pressure           400 non-null    str
 10  heart_rate               400 non-null    int64
 11  daily_steps              400 non-null    int64
 12  sleep_disorder           110 non-null    str
dtypes: float64(2), int64(6), str(5)
memory usage: 40.8 KB

In [40]:
# 3.数据清洗
df.isna().sum()
# 数据填充
# df['sleep_disorder'].value_counts()
df.drop(columns=['sleep_disorder'],inplace=True)
df.isna().sum()

person_id                  0
gender                     0
age                        0
occupation                 0
sleep_duration             0
sleep_quality              0
physical_activity_level    0
stress_level               0
bmi_category               0
blood_pressure             0
heart_rate                 0
daily_steps                0
dtype: int64

In [53]:
# 数据特征的构造
print(df['bmi_category'].value_counts())
df['gender'] = df['gender'].astype('category')
df['occupation'] = df['occupation'].astype('category')
df['bmi_category'] = df['bmi_category'].astype('category')
df.head()
df[['high','low']] = df['blood_pressure'].str.split('/',expand=True)
labels = ['差','中','优']
df['quality_level'] = pd.cut(df['sleep_quality'],bins=3,labels=labels)
labels = ['青少年','中年','老年']
df['age_level'] = pd.cut(df['age'],bins=[0,20,50,100],labels=labels)
df

bmi_category
Overweight     109
Underweight    102
Obese           98
Normal          91
Name: count, dtype: int64

,person_id,gender,age,occupation,sleep_duration,sleep_quality,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,high,low,quality_level,age_level
0,1,Male,29,Manual Labor,7.4,7.0,41,7,Obese,124/70,91,8539,124,70,中,中年
1,2,Female,43,Retired,4.2,4.9,41,5,Obese,131/86,81,18754,131,86,中,中年
2,3,Male,44,Retired,6.1,6.0,107,4,Underweight,122/70,81,2857,122,70,中,中年
3,4,Male,29,Office Worker,8.3,10.0,20,10,Obese,124/72,55,6886,124,72,优,中年
4,5,Male,67,Retired,9.1,9.5,19,4,Overweight,133/78,97,14945,133,78,优,老年
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,Female,36,Student,4.5,7.9,73,7,Normal,118/66,64,14497,118,66,优,中年
396,397,Female,45,Manual Labor,6.0,6.1,72,8,Obese,132/80,65,12848,132,80,中,中年
397,398,Female,30,Student,5.3,6.5,58,10,Obese,125/76,66,15255,125,76,中,中年
398,399,Female,41,Retired,11.0,9.1,73,9,Obese,130/75,75,6567,130,75,优,中年
399,400,Male,37,Retired,5.8,7.0,41,6,Normal,118/70,51,18079,118,70,中,中年

In [ ]:
# 数据的统计、分析
print(df['bmi_category'].value_counts())

In [59]:
# 根据不同的bmi分组，睡眠质量
result = df.groupby(['bmi_category']).agg({
    'sleep_quality':['mean'],
    'sleep_duration':['mean'],
    'stress_level':['mean']
})
result = result.round(2)
print(result)

             sleep_quality sleep_duration stress_level
                      mean           mean         mean
bmi_category
Normal                6.34           7.79         4.86
Obese                 6.19           8.07         5.77
Overweight            6.10           8.27         5.64
Underweight           5.90           7.98         5.56